In [1]:
import numpy as np

# Advance Array Manipulation

In [2]:
arr = np.array(range(1,21))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
A = np.array([[1,2],[3,4]])
print(A)
B = np.array([[5,6],[7,8]])
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
# Stacking Array
A = np.arange(1,5)
print(A)
B = np.arange(5,9)
print(B)

[1 2 3 4]
[5 6 7 8]


In [12]:
vs = np.vstack((A,B))
print(vs)
np.ndim(vs)

[[1 2 3 4]
 [5 6 7 8]]


2

In [11]:
hs = np.hstack((A,B))
print(hs)
np.ndim(hs)

[1 2 3 4 5 6 7 8]


1

In [8]:
col_st = np.column_stack((A,B))
print(col_st)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [10]:
np.ndim(col_st)

2