In [2]:
import numpy as np

# Arithmetic Operations

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [4]:
arrAdd = a1 + a2
print(arrAdd)

[ 7  9 11 13 15]


In [5]:
arrSub = a1 - a2
print(arrSub)

[-5 -5 -5 -5 -5]


In [6]:
arrMul = a1 * a2
print(arrMul)

[ 6 14 24 36 50]


In [7]:
arrDivide = a1/a2
print(arrDivide)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [8]:
arrFloor = a1//a2
print(arrFloor)

[0 0 0 0 0]


In [9]:
arrExpon = a1 ** a2
print(arrExpon)

[      1     128    6561  262144 9765625]


In [10]:
# Broad Casting

l = [10,20,30,40,50]
arr = np.array(l)
print(arr)

[10 20 30 40 50]


In [12]:
arr + 10

array([20, 30, 40, 50, 60])

In [13]:
arr2 = np.arange(1,26).reshape(5,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
arr2 +10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [15]:
# Deep and Shallow copy

arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice = arr[:5]
slice = slice*10
print(slice)

[10 20 30 40 50]


In [21]:
# Matrix Operations

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print()
print(B)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [22]:
A @ B

array([[19, 22],
       [43, 50]])

In [23]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])