In [1]:
import numpy as np

In [2]:
# basic array creation
ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [5]:
a = [1,2,6,"hello"]
np.array(a)
# print(a)

array(['1', '2', '6', 'hello'], dtype='<U21')

In [11]:
li = [[[1,2,3],[4,5,6],[7,8,9]]]
li

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [12]:
li = np.array(li)
print()
np.ndim(li)

3

In [13]:
# array generation function
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.zeros(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
arr = np.ones((4,6))
print(arr)
np.ndim(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


2

In [7]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [8]:
# Random Generation functions
np.random.rand(10)

array([0.52067854, 0.03282801, 0.75357048, 0.58691947, 0.96605131,
       0.69722027, 0.34339729, 0.97837959, 0.63260974, 0.68214161])

In [11]:
np.random.randint(9)

8

In [13]:
np.random.randint(10,20,10)

array([10, 14, 17, 11, 17, 14, 19, 10, 14, 16], dtype=int32)

In [15]:
# array attributes
arr = np.array([[10,20],[30,40]])
arr

array([[10, 20],
       [30, 40]])

In [16]:
arr.shape

(2, 2)

In [17]:
arr.size

4

In [18]:
arr.dtype

dtype('int64')

In [19]:
# array methods

arr.min()

np.int64(10)

In [20]:
arr.max()

np.int64(40)

In [21]:
arr.sum()

np.int64(100)

In [10]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr
print(np.ndim(arr))

2


In [11]:
print(arr.sum())

21


In [12]:
np.sum(arr, axis = 0)

array([5, 7, 9])

In [13]:
np.sum(arr, axis = 1)

array([ 6, 15])

In [14]:
arr.mean()

np.float64(3.5)

In [15]:
arr.std()  # standard deviation

np.float64(1.707825127659933)

In [16]:
arr.argmax() # its return index

np.int64(5)

In [17]:
arr.argmin()

np.int64(0)

In [22]:
# reshaping and resizing

ar = np.arange(1,31)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
x =  ar.reshape(6,5)
x
print(np.ndim(x))

2


In [28]:
x =  ar.reshape(1,6,5)
print(x)
print(np.ndim(x))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
3
