In [1]:
import numpy as np

In [2]:
# basic array creation
ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [5]:
a = [1,2,6,"hello"]
np.array(a)
# print(a)

array(['1', '2', '6', 'hello'], dtype='<U21')

In [11]:
li = [[[1,2,3],[4,5,6],[7,8,9]]]
li

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [12]:
li = np.array(li)
print()
np.ndim(li)

3

In [13]:
# array generation function
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.zeros(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
