In [2]:
import numpy as np

In [2]:
# basic array creation
ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [5]:
a = [1,2,6,"hello"]
np.array(a)
# print(a)

array(['1', '2', '6', 'hello'], dtype='<U21')

In [11]:
li = [[[1,2,3],[4,5,6],[7,8,9]]]
li

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [12]:
li = np.array(li)
print()
np.ndim(li)

3

In [13]:
# array generation function
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.zeros(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
arr = np.ones((4,6))
print(arr)
np.ndim(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


2

In [7]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [8]:
# Random Generation functions
np.random.rand(10)

array([0.52067854, 0.03282801, 0.75357048, 0.58691947, 0.96605131,
       0.69722027, 0.34339729, 0.97837959, 0.63260974, 0.68214161])

In [11]:
np.random.randint(9)

8

In [13]:
np.random.randint(10,20,10)

array([10, 14, 17, 11, 17, 14, 19, 10, 14, 16], dtype=int32)