In [6]:
import numpy as np

In [19]:
# Valid Sudoko

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
print(s)
np.ndim(s)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


2

In [8]:
# s = np.sum(s)
# s

In [9]:
# I want row wise sum
# s = np.sum(s, axis = 1)
# s

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [15]:
# s[s == 45]

array([], dtype=int64)

In [17]:
# I want column wise sum
s = np.sum(s, axis = 0)
print(s)

[45 45 45 45 45 45 45 45 45]


In [20]:
ar = s[0:3, 0:3]
print(ar)

[[5 3 4]
 [6 7 2]
 [1 9 8]]


In [21]:
# General Questions

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


In [22]:
#Get the shape of the matrix.

data.shape

(5, 3)

In [23]:
#Find the average age of students.

np.mean(data[:,0])

np.float64(18.4)

In [24]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [25]:
#Find the highest Science mark.

np.max(data[:,2])

np.int64(95)

In [27]:
#Get details of the student who scored more than 90 in Math.

data[data[:,1] > 90]

array([[19, 92, 88]])

In [28]:
#Increase Math marks of all students by 5.

data[:,1]+5

array([90, 97, 81, 70, 95])

In [35]:
#Find how many students are younger than 19.

len(data[data[:,0] <19])

3

In [42]:
#Calculate the average marks in each subject (column-wise mean).

avg = np.average(data[:,1:], axis = 0)
print(avg)

[81.6 83.2]


In [46]:
#Get data of students who scored at least 80 in both subjects.

data[(data[:,1]>=80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [47]:
#Replace all Science marks < 75 with 0.

data[:, 2] = np.where(data[:, 2] < 75, 0, data[:, 2])
print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
