In [1]:
import numpy as np

In [2]:
# basic array creation
ar = np.array([1,2,3,4,5])
print(ar)

[1 2 3 4 5]


In [5]:
a = [1,2,6,"hello"]
np.array(a)
# print(a)

array(['1', '2', '6', 'hello'], dtype='<U21')

In [11]:
li = [[[1,2,3],[4,5,6],[7,8,9]]]
li

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [12]:
li = np.array(li)
print()
np.ndim(li)

3

In [13]:
# array generation function
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.zeros(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# indexing and slicing of vectors

arr = np.arange(11,21)
print(arr)



[11 12 13 14 15 16 17 18 19 20]


In [3]:
print(arr[9])

20


In [5]:
arr[3:9]
arr[2::3]

array([13, 16, 19])

In [6]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [8]:
arr[0]

array([1, 2, 3, 4, 5])

In [9]:
arr[5]

array([26, 27, 28, 29, 30])

In [10]:
arr[0,0]

np.int64(1)

In [12]:
arr[0,4]

np.int64(5)

In [13]:
arr[5,4]

np.int64(30)

In [15]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])